#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
git config core.hooksPath .githooks

# run from the root of the repo
# If your filesystem is not case-sensitive you can use
echo $(pwd)
.githooks/replace_by_git_vars.sh .githooks/README.template.md

# Example:
# [![Integration Tests](https://github.com/{{ repository.name }}/actions/workflows/integration-tests.yaml/badge.svg?branch={{ current.branch }})](https://github.com/{{ repository.name }}/actions/workflows/integration-tests.yaml?query=branch%3A{{ current.branch }})

